stages:
  - linting

pylint:
  stage: linting
  image: python:latest
  script:
    - pip install pylint
    - pylint --exit-zero ./backend # Run pylint on your project directory
    - PYLINT_SCORE=$(pylint --output-format=text ./backend | grep "Your score:" | awk '{print $NF}')
    - echo "Pylint Score: $PYLINT_SCORE"
    - if (( $(echo "$PYLINT_SCORE < 9" | bc -l) )); then exit 1; fi # Fail if score is less than 9
  only:
    - main
    - dev
